version: '3'
services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql-app
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test_database
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=test
  app:
    build:
      context: ./docker/construct_app      # Dockerfile保存場所
      dockerfile: Dockerfile-app    # Dockerfileファイル名
    image: umks-app                  # イメージ名
    container_name: umks-app         # コンテナ名
    ports:                          # ポート接続
      - 3000:3000
    volumes:                        # mount workdir
      - ./myapp:/src
    command: [sh, -c, npm install && node app.js]
  web:
    build:
      context: ./docker/construct_web      # Dockerfile保存場所
      dockerfile: Dockerfile-web    # Dockerfileファイル名
    image: umks-web      # docker image name
    container_name: umks-web       # docker container name
    ports:
      - 80:80
